config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'static_pages#home'
  post 'twilio/voice' => 'twilio#voice'
  post 'notifications/notify' => 'notifications#notify'
  post 'twilio/status' => 'twilio#status'
  post 'twilio/inbound' => 'twilio#inbound'

  resources :campaigns
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
	belongs_to :user
	has_many :visitors
	has_many :short_urls
	has_many :short_url_logs
	has_many :campaign_tags
end

app/models/campaign_tag.rb
class CampaignTag < ApplicationRecord
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
end

app/models/short_url_log.rb
class ShortUrlLog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :campaigns
end

app/models/visitor.rb
class Visitor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :phone, :company])
  		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name, :email, :phone, :company])
  			
  	end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
	def new
		@campaign = Campaign.new

	end

	def create
		@campaign = Campaign.new(
			user_id: current_user.id,
			campaign_phone: params[:campaign][:campaign_phone],
			campaign_keyword: params[:campaign][:campaign_keyword],
			destination_url: params[:campaign][:destination_url],
			campaign_description: params[:campaign][:campaign_description],
			active: params[:campaign][:active],
			start_time: params[:campaign][:start_time],
			end_time: params[:campaign][:end_time]
			)
		@campaign.save

		redirect_to root_path
	end

	def edit
		@campaign = Campaign.find_by(id: params[:id])
	end

	def update
		@campaign = Campaign.find_by(id: params[:id])

		if @campaign.update_attributes(campaign_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	private

	def campaign_params
		params.require(:campaign).permit(:user_id, :campaign_phone, :campaign_keyword, :destination_url, :campaign_description, :active, :start_time, :end_time)
	end
end

app/controllers/concerns/webhookable.rb
module Webhookable
extend ActiveSupport::Concern

	def set_header
      		response.headers["Content-Type"] = "text/xml"
	end

	def render_twiml(response)
      		render text: response.text
	end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
 
  skip_before_action :verify_authenticity_token
 
  def notify
  	account_sid = 'AC0e677fee0759f3c09a0179c908367979'
  	account_auth_token = '7f228d90fb8c958b022dddefc65c1919'

    client = Twilio::REST::Client.new account_sid, account_auth_token
  	message = client.messages.create from: '+13053631650', to: '+17865645859', body: 'Learning to send SMS you are.', media_url: 'http://linode.rabasa.com/yoda.gif', status_callback: request.base_url + '/twilio/status'


  	render plain: message.status
  end

 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		if user_signed_in?
			@campaigns = current_user.campaigns.order('id ASC')
		end	
	end
end

app/controllers/twilio_controller.rb
require 'twilio-ruby'

class TwilioController < ApplicationController
  include Webhookable

  after_filter :set_header

  skip_before_action :verify_authenticity_token


  def voice
    response = Twilio::TwiML::Response.new do |r|
      r.Say 'Hey there. Congrats on integrating Twilio into your Rails 4 app.', :voice => 'alice'
         r.Play 'http://linode.rabasa.com/cantina.mp3'
    end

    render_twiml response
  end

  def inbound
    account_sid = 'AC0e677fee0759f3c09a0179c908367979'
    account_auth_token = '7f228d90fb8c958b022dddefc65c1919'
    
    @client = Twilio::REST::Client.new account_sid, account_auth_token
 
 # Assigning the incoming visitor number, number visitor texted, and keyword texted to variables 
    visitor = params[:From]
    campaign_number = params[:To]
    keyword = params[:Body]

# Checking to see if phone # visitor texts belongs to a campaign, assigning that campaign to variable campaign_visited
      campaign_visited = Campaign.find { |campaign| campaign.campaign_phone == campaign_number}

    if Visitor.exists?(phone: visitor)
      message = @client.messages.create from: campaign_number, to: visitor, body: 'Great! What’s your email (we’ll send the link there)?', status_callback: request.base_url + '/twilio/status'
      
      if 
      # puts campaign_visited
    else
      @visitor = Visitor.create(
        id: params[:SmsSid],
        phone: params[:From]
        )
      message = @client.messages.create from: campaign_number, to: @visitor.phone, body: 'Great! What’s your email (we’ll send the link there)?', status_callback: request.base_url + '/twilio/status'
    end



    # @client.account.incoming_phone_numbers.list.each do |number|
    #   puts number.phone_number
    # end

    render plain: message.status
  end

  def status
    render_twiml Twilio::TwiML::Response.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/campaigns/edit.html.erb
<h2>Edit your campaign</h2>

<h2>Create a new campaign</h2>
<%= form_for @campaign do |f| %>
  <div class="field">
    <%= f.label :campaign_phone %><br />
    <%= f.text_field :campaign_phone, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :campaign_keyword %><br />
    <%= f.text_field :campaign_keyword %>
  </div>  

  <div class="field">
    <%= f.label :destination_url %><br />
    <%= f.text_field :destination_url %>
  </div>  

  <div class="field">
    <%= f.label :campaign_description %><br />
    <%= f.text_field :campaign_description %>
  </div>  

  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>    

  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_field :start_time %>
  </div>  

<div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_field :end_time %>
  </div>  
	
	<%= f.submit 'Change Campaign', :class => 'btn btn-default btn-block' %>
<% end %>
<%= link_to 'Home', root_path %>

app/views/campaigns/new.html.erb
<h2>Create a new campaign</h2>
<%= form_for @campaign do |f| %>
  <div class="field">
    <%= f.label :campaign_phone %><br />
    <%= f.text_field :campaign_phone, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :campaign_keyword %><br />
    <%= f.text_field :campaign_keyword %>
  </div>  

  <div class="field">
    <%= f.label :destination_url %><br />
    <%= f.text_field :destination_url %>
  </div>  

  <div class="field">
    <%= f.label :campaign_description %><br />
    <%= f.text_field :campaign_description %>
  </div>  

  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>    

  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_field :start_time %>
  </div>  

<div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_field :end_time %>
  </div>  
	
	<%= f.submit 'Create Campaign', :class => 'btn btn-default btn-block' %>
<% end %>
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TextForLink</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
Wassuh, 
<% if current_user %>

<div>
Your profile:
<ul>
	<li><b>Email:</b> <%= current_user.email %></li>
	<li><b>First name:</b> <%= current_user.first_name %></li>
	<li><b>Last name:</b> <%= current_user.last_name %></li>
	<li><b>Phone:</b> <%= current_user.phone %></li>
	<li><b>Company:</b> <%= current_user.company %></li>
	</ul>
<% end %>

</div>

<div>
<% if current_user.campaigns %>
	<b>Your campaigns:</b>
	<% @campaigns.each do |campaign| %>
		<div class="user_campaign">
			<ul>
				<li><b>User ID:</b> <%= campaign.user_id  %></li>
				<li><b>Campaign ID:</b> <%= campaign.id  %></li>
				<li><b>Campaign Phone Number:</b> <%= campaign.campaign_phone  %></li>
				<li><b>Campaign Keyword:</b> <%= campaign.campaign_keyword  %></li>
				<li><b>Destination URL:</b> <%= campaign.destination_url  %></li>
				<li><b>Created at:</b> <%= campaign.created_at  %></li>
				<li><b>Campaign Description:</b> <%= campaign.campaign_description  %></li>
				<li><b>Active?:</b> <%= campaign.active  %></li>
				<li><b>Start Time:</b> <%= campaign.start_time  %></li>
				<li><b>End Time:</b> <%= campaign.end_time  %></li>
				<li><%= link_to 'Edit Campaign', edit_campaign_path(campaign.id) %></li>
			</ul>
		</div>
	<% end %>
<% end %>

<br>
<%= link_to('Create a new campaign', new_campaign_path) %>
</div>

<div>
	<% if !user_signed_in? %>
	<%= link_to('Sign up', new_user_registration_path)  %>
	<%= link_to('Log in', new_user_session_path)  %>
	<% end %>
	<br>
	<br>
	<%= link_to 'Log out', destroy_user_session_path, :method => :delete  %>

</div>